### ISSUE TITLE
Remove references to HCA from codebase

### ISSUE THREAD

**Issue by chmreid** [DataBiosphere/data-store-kharon#2]
- [x] Update readme to remove mentions of HCA (#3)

- [x] Update source code to remove HCA-related naming conventions (#13)

- [x] Update documentation to remove references to HCA (#7)

- [x] Update tests to remove references to HCA (#15)
